### ISSUE TITLE
Visualisation ToDo

### ISSUE THREAD

**Issue by Konrad1991** [ComPlat/Biostats#3]
- [x] Sigmoidal fit als fit method
- [ ] possibility to choose the interval of the x and y axis
- [ ] Size of plots insufficient when many plots are generated
