### ISSUE TITLE
Docu ToDo

### ISSUE THREAD

**Issue by Konrad1991** [ComPlat/Biostats#4]
- [x] Add hovering documentation for each button 
- [x] Add question mark documentation for each tab
- [x] Add a question mark editor to the formula editor. Make an example for each operation with a example dataframe and if possible with a plot. 
- [x] Explain the working with colnames
